export type ComponentStatus = "ready" | "planned";

export type ChordComponentManifest = {
  id: string;
  displayName: string;
  figmaName: string;
  nodeId: string;
  componentKey: string;
  type: "COMPONENT" | "COMPONENT_SET";
  description: string;
  variantCount: number;
  variantAxes: Record<string, readonly string[]>;
  status: ComponentStatus;
};

export const chordComponents = [
  {
    id: "avatar",
    displayName: "Avatar",
    figmaName: "[V2] Avatar",
    nodeId: "62973:7556",
    componentKey: "33d955018e09fb10ab89cefc8f00f2662a2b0e39",
    type: "COMPONENT_SET",
    description: "사람, 아티스트, 그룹, 공식 커뮤니티를 대표하는 이미지형 컴포넌트",
    variantCount: 44,
    variantAxes: { Mode: ["Default", "Fixed"], Type: ["Circle", "Squircle"], Size: ["Tiny", "XXXSmall", "XXSmall", "XSmall", "Small", "Medium", "Large", "XLarge", "XXLarge", "XXXLarge", "XXXXLarge"] },
    status: "planned",
  },
  {
    id: "badge-dot",
    displayName: "Badge Dot",
    figmaName: "Badge_Dot",
    nodeId: "8451:112783",
    componentKey: "d1ea898a9e908e7470a7518abae5b45c18e0a58a",
    type: "COMPONENT_SET",
    description: "탐색 항목이나 아이콘에 알림 또는 상태가 있음을 점 형태로 표시하는 배지 컴포넌트",
    variantCount: 12,
    variantAxes: { Mode: ["Default", "Fixed"], Size: ["Small", "Medium", "Large"], Outline: ["OFF", "ON"] },
    status: "ready",
  },
  {
    id: "badge-number",
    displayName: "Badge Number",
    figmaName: "Badge_Number",
    nodeId: "8451:113030",
    componentKey: "0ec884a8ce648a69360a64bc9b883cd0b3cc948d",
    type: "COMPONENT_SET",
    description: "탐색 항목이나 아이콘에 알림 수량 또는 신규 상태를 라벨로 표시하는 배지 컴포넌트",
    variantCount: 4,
    variantAxes: { Mode: ["Default", "Fixed"], Type: ["Number", "New"] },
    status: "ready",
  },
  {
    id: "text-button",
    displayName: "Text Button",
    figmaName: "Text Button",
    nodeId: "52753:39618",
    componentKey: "70d2a20bcdfe3ac7a3c3190410d9a255d8783e1d",
    type: "COMPONENT_SET",
    description: "사용자가 선택이나 행동을 실행할 수 있게 하는 텍스트 중심 버튼 컴포넌트",
    variantCount: 576,
    variantAxes: { Mode: ["Default", "Fixed"], Type: ["Filled", "Outlined_color", "Outlined_gray", "Ghost"], Size: ["XLarge(52)", "Large(44)", "Medium(40)", "Small(36)", "XSmall(32)", "XXSmall(24)"], "Button Color": ["Black(Gray Ghost 미적용)", "Default (Gray Ghost 단일컬러)"], Status: ["Default", "Hover", "Loading", "Disabled"], Radius: ["off", "on"] },
    status: "ready",
  },
  {
    id: "icon-button",
    displayName: "Icon Button",
    figmaName: "Icon Button",
    nodeId: "54093:38777",
    componentKey: "b60ecb5e664ce4e19bd9b11dd521d9b710d711df",
    type: "COMPONENT_SET",
    description: "아이콘만으로 주요 행동을 실행하는 정사각 버튼 컴포넌트",
    variantCount: 192,
    variantAxes: { Mode: ["Default", "Fixed"], Type: ["Filled", "Outlined"], Size: ["XLarge(52)", "Medium(40)", "Small(36)", "XXSmall(24)"], State: ["Default", "Hover", "Disabled"], Radius: ["on", "off"], "Button Color": ["Default", "Black"] },
    status: "ready",
  },
  {
    id: "checkbox",
    displayName: "Checkbox",
    figmaName: "[V2] Checkbox",
    nodeId: "60365:40276",
    componentKey: "80eebb7d094726a1a9e864931f4347d76008ca25",
    type: "COMPONENT_SET",
    description: "단일 확인 또는 복수 항목 선택에 사용하는 선택 컨트롤",
    variantCount: 12,
    variantAxes: { Mode: ["Default", "Fixed"], Type: ["Circle", "Square"], Status: ["Default", "Enabled", "Disabled"] },
    status: "ready",
  },
  {
    id: "chips",
    displayName: "Chips",
    figmaName: "[V2] Chips",
    nodeId: "59869:78921",
    componentKey: "6f1fa3aadc347f4c8c2f26405695b2415dbdcb95",
    type: "COMPONENT_SET",
    description: "옵션, 필터, 탭성 선택지를 작은 단위로 보여주고 사용자가 하나 또는 여러 개를 선택하기 위해 사용하는 선택 컴포넌트",
    variantCount: 100,
    variantAxes: { Mode: ["Default", "Fixed"], Size: ["Small", "Medium"], Type: ["Text", "Icon", "Image (Only Medium)"], State: ["Default", "Filled_Selected", "Outlined_Selected", "Filled_Disabled", "Outlined_Disabled"], Radius: ["ON", "OFF"] },
    status: "planned",
  },
  {
    id: "divider",
    displayName: "Divider",
    figmaName: "[V1] Divider",
    nodeId: "10379:40800",
    componentKey: "5153f6a88c72583fd7bf2923e355e3b5d0e85773",
    type: "COMPONENT_SET",
    description: "콘텐츠 영역을 시각적으로 구분하는 수평 구분선 컴포넌트",
    variantCount: 12,
    variantAxes: { Mode: ["Default", "Fixed"], Height: ["1", "2", "8"], Style: ["Default-50a", "Default-50a-2"] },
    status: "ready",
  },
  {
    id: "dropdown-box",
    displayName: "Dropdown Box",
    figmaName: "Dropdown_Box",
    nodeId: "60730:9605",
    componentKey: "97601b8a3636233ad6892ba3ecb2fa22f59e9546",
    type: "COMPONENT_SET",
    description: "제공된 선택 항목 중 하나를 고르기 위한 입력형 선택 컴포넌트",
    variantCount: 14,
    variantAxes: { Mode: ["Default", "Fixed"], State: ["Default", "Pressed (Hover)", "Enabled_Down", "Enabled_Up", "Completed", "Error", "Disabled"] },
    status: "planned",
  },
  {
    id: "list-item-native",
    displayName: "List Item Native",
    figmaName: "[V2] List_Item_Native",
    nodeId: "57343:18628",
    componentKey: "e120970b1638c0fa7a5b7638923eb91479384ebe",
    type: "COMPONENT_SET",
    description: "네이티브 앱 목록에서 대표 이미지, 제목/보조문구, 우측 보조 액션을 한 행으로 조합하는 리스트 아이템 컴포넌트",
    variantCount: 12,
    variantAxes: { Mode: ["Default", "Fixed"], Size: ["Small", "Medium"], Status: ["Default", "Hover(Pressed)", "Disabled"] },
    status: "planned",
  },
  {
    id: "list-item-web",
    displayName: "List Item Web",
    figmaName: "[V2] List_Item_Web",
    nodeId: "69579:9043",
    componentKey: "42c19f42926776126ff312006b4505a4e03a905a",
    type: "COMPONENT_SET",
    description: "웹 목록에서 대표 이미지, 제목/보조문구, 우측 보조 액션을 중앙 정렬 행으로 조합하는 리스트 아이템 컴포넌트",
    variantCount: 12,
    variantAxes: { Mode: ["Default", "Fixed"], Size: ["Small", "Medium"], Alignment: ["Center"], States: ["Default", "Hover(Pressed)", "Disabled"] },
    status: "planned",
  },
  {
    id: "menu",
    displayName: "Menu",
    figmaName: "[V2] Menu",
    nodeId: "25963:37235",
    componentKey: "f1e30b43648b4839e2cd69b1de633dd29a408fed",
    type: "COMPONENT_SET",
    description: "현재 맥락에서 선택 가능한 여러 액션이나 항목을 짧게 보여주는 오버레이 선택 컴포넌트",
    variantCount: 2,
    variantAxes: { Mode: ["Default", "Fixed"] },
    status: "planned",
  },
  {
    id: "linear-progress-indicator",
    displayName: "Linear Progress Indicator",
    figmaName: "Linear_Progress_Indicator",
    nodeId: "9003:21727",
    componentKey: "42d64503b19a20dd5a6f7ea05e3c61cc3e75e9b7",
    type: "COMPONENT_SET",
    description: "작업 진행 상태를 수평 막대로 표시하는 진행 인디케이터",
    variantCount: 6,
    variantAxes: { Mode: ["Default", "Fixed"], Rounded: ["ON", "OFF"], Height: ["2", "4"] },
    status: "ready",
  },
  {
    id: "circular-progress-indicator",
    displayName: "Circular Progress Indicator",
    figmaName: "Circular_Progress_Indicator",
    nodeId: "9003:21751",
    componentKey: "52969b5595e5042dda34b6a45dbb86939887af5c",
    type: "COMPONENT_SET",
    description: "컴포넌트 내부 처리 중 상태를 원형 진행 표시로 보여주는 인디케이터",
    variantCount: 2,
    variantAxes: { Mode: ["Default", "Fixed"] },
    status: "ready",
  },
  {
    id: "search",
    displayName: "Search",
    figmaName: "[V2] Search",
    nodeId: "59722:17972",
    componentKey: "cbcd2baf8a758cd859c194359b69faf7fa3e543a",
    type: "COMPONENT_SET",
    description: "키워드를 입력해 원하는 정보나 결과를 찾는 검색 입력 컴포넌트",
    variantCount: 6,
    variantAxes: { Mode: ["Default", "Fixed"], State: ["Default", "Focus", "Typing"] },
    status: "planned",
  },
  {
    id: "snackbar",
    displayName: "Snackbar",
    figmaName: "[V2] Snackbar",
    nodeId: "63694:5774",
    componentKey: "1d2be6f3586d1004dcb93f999e630377fe2a18c7",
    type: "COMPONENT_SET",
    description: "작업 결과를 알려주고 필요한 경우 선택적 후속 조치를 제공하는 하단 피드백 컴포넌트",
    variantCount: 2,
    variantAxes: { Mode: ["Default", "Fixed"] },
    status: "planned",
  },
  {
    id: "stepper",
    displayName: "Stepper",
    figmaName: "[V2] Stepper",
    nodeId: "61604:4394",
    componentKey: "684550ae4653da74717f2599c3da1bb7b7640d73",
    type: "COMPONENT_SET",
    description: "상품 수량처럼 작은 범위의 숫자 값을 직접 입력하거나 감소와 증가 버튼으로 조정하는 입력 컴포넌트",
    variantCount: 6,
    variantAxes: { Mode: ["Default", "Fixed"], State: ["Default", "Disabled", "Typing"] },
    status: "planned",
  },
  {
    id: "tabs",
    displayName: "Tabs",
    figmaName: "[V2] Tabs",
    nodeId: "65172:10165",
    componentKey: "12eee519d7ee66e179cb03c579962a37beba7e7f",
    type: "COMPONENT_SET",
    description: "한 화면 안에서 관련 카테고리나 콘텐츠 그룹을 빠르게 전환하는 탭 탐색 컴포넌트",
    variantCount: 16,
    variantAxes: { Mode: ["Default", "Fixed"], Style: ["Filled", "Line"], Type: ["Text", "Icon", "Image"], Size: ["Small", "Medium", "Large"] },
    status: "planned",
  },
  {
    id: "text-fields",
    displayName: "Text Fields",
    figmaName: "[V2] Text_Fields",
    nodeId: "62030:25225",
    componentKey: "1cd268687529359f71d915dd915ac2eac7eb3fa4",
    type: "COMPONENT_SET",
    description: "사용자가 텍스트를 입력하거나 편집하고 입력 상태와 피드백을 확인하는 폼 입력 컴포넌트",
    variantCount: 20,
    variantAxes: { Mode: ["Default", "Fixed"], Lines: ["Single", "Multi"], Status: ["Default", "Focus", "Typing", "Error", "Disabled"] },
    status: "planned",
  },
  {
    id: "thumbnail",
    displayName: "Thumbnail",
    figmaName: "[V2] Thumbnail",
    nodeId: "50545:51014",
    componentKey: "d0a05143f1a3867b7d8d30eacf939b885d41e0eb",
    type: "COMPONENT_SET",
    description: "콘텐츠 대표 이미지를 정해진 비율, 반경, 선택 오버레이와 함께 표시하는 미디어 썸네일 컴포넌트",
    variantCount: 12,
    variantAxes: { Type: ["Default"], Ratio: ["1:1", "2:3", "3:2", "4:3", "16:9", "9:16"], Radius: ["ON", "OFF"] },
    status: "planned",
  },
  {
    id: "title-header",
    displayName: "Title Header",
    figmaName: "Title Header",
    nodeId: "64450:27844",
    componentKey: "33261ba4635ef136dd94de771e9ded865a98c6d4",
    type: "COMPONENT_SET",
    description: "화면 안에서 현재 콘텐츠 묶음의 제목과 보조 정보를 표시하는 48px 높이의 헤더 패턴",
    variantCount: 4,
    variantAxes: { Mode: ["Default", "Fixed"], Align: ["Left", "Center"] },
    status: "planned",
  },
  {
    id: "top-navigation",
    displayName: "Top Navigation",
    figmaName: "Top Navigation",
    nodeId: "64450:39560",
    componentKey: "f53f182c4c02ac61fdb2d8bcdb0304f6ed4be48d",
    type: "COMPONENT_SET",
    description: "화면 상단에서 현재 페이지 제목과 맥락적 이동 또는 액션 아이콘을 제공하는 탐색 컴포넌트",
    variantCount: 32,
    variantAxes: { Mode: ["Default", "Fixed"], "Text Type": ["None", "Title", "Title + Subtitle", "Logo", "Search", "Segment", "Tab", "Custom"], "Scroll Bg": ["OFF", "ON"] },
    status: "planned",
  },
  {
    id: "toast",
    displayName: "Toast",
    figmaName: "[V2] Toast",
    nodeId: "63694:4595",
    componentKey: "c582282238f4497a69ce1f3a82bd4c59723de883",
    type: "COMPONENT_SET",
    description: "사용자 작업에 대한 짧은 시스템 상태 피드백을 자동으로 사라지는 하단 메시지로 전달하는 컴포넌트",
    variantCount: 2,
    variantAxes: { Mode: ["Default", "Fixed"] },
    status: "planned",
  },
  {
    id: "radio",
    displayName: "Radio",
    figmaName: "[V2] Radio",
    nodeId: "59215:200965",
    componentKey: "a04bcc0355ca5db25efdc00cdfc68958db3f5976",
    type: "COMPONENT_SET",
    description: "여러 항목 중 하나만 선택해야 하는 상황에서 사용하는 단일 선택 컨트롤",
    variantCount: 6,
    variantAxes: { Mode: ["Default", "Fixed"], Status: ["Default", "Enabled", "Disabled"] },
    status: "ready",
  },
  {
    id: "scrim-overlay",
    displayName: "Scrim Overlay",
    figmaName: "Scrim_Overlay",
    nodeId: "10482:75325",
    componentKey: "82556da89c0795003b5b07261ac8dc65fb09da1c",
    type: "COMPONENT",
    description: "배경 콘텐츠 위에 반투명 레이어를 덮어 전면 UI와 배경 사이의 위계를 만드는 오버레이",
    variantCount: 1,
    variantAxes: {},
    status: "ready",
  },
  {
    id: "scrollbar",
    displayName: "Scrollbar",
    figmaName: "Scrollbar",
    nodeId: "27782:8837",
    componentKey: "ec2d17107a68bb443f80245ab791fb69380f0a50",
    type: "COMPONENT_SET",
    description: "스크롤 가능한 콘텐츠의 현재 위치와 이동 가능성을 보여주는 스크롤 컨트롤",
    variantCount: 3,
    variantAxes: { Mode: ["Default", "Hover", "Dragging"] },
    status: "ready",
  },
  {
    id: "select-number-box",
    displayName: "Select Number Box",
    figmaName: "Select_Number_Box",
    nodeId: "12436:362",
    componentKey: "9d3d023e0d5060cdbcb54f40ff6c1df7a0c333a5",
    type: "COMPONENT_SET",
    description: "선택된 요소의 순서나 99+ 초과 상태를 작은 원형 숫자로 표시하는 상태 표시 컴포넌트",
    variantCount: 6,
    variantAxes: { Mode: ["Default", "Fixed"], State: ["Default", "Selected", "Over"] },
    status: "ready",
  },
  {
    id: "skeleton",
    displayName: "Skeleton",
    figmaName: "Skeleton",
    nodeId: "12447:42302",
    componentKey: "646e648144ff6565de0d221e746dce3d4883ac5a",
    type: "COMPONENT_SET",
    description: "콘텐츠 로딩 중 실제 콘텐츠 영역의 형태를 미리 보여주는 플레이스홀더 컴포넌트",
    variantCount: 12,
    variantAxes: { Mode: ["Default", "Fixed"], Type: ["Rectangle", "Circle", "Text"], Size: ["Small", "Medium"] },
    status: "ready",
  },
  {
    id: "pagination-dot",
    displayName: "Pagination Dot",
    figmaName: "Pagination_Dot(v2)",
    nodeId: "62324:12061",
    componentKey: "6dc90bf874beb759995aee563475cf96c3aa9a58",
    type: "COMPONENT_SET",
    description: "정확한 페이지 번호보다 현재 위치와 콘텐츠 흐름을 간단히 보여줄 때 사용하는 점 형태 페이지네이션",
    variantCount: 40,
    variantAxes: { Mode: ["Default", "Fixed"], Dots: ["1", "2", "3", "4", "5"], Selection: ["1", "2", "3", "4", "5", "More"] },
    status: "planned",
  },
  {
    id: "pagination-list",
    displayName: "Pagination List",
    figmaName: "Pagination_List(v2)",
    nodeId: "61753:7839",
    componentKey: "cf936b6328942bcd5428cadb0d709f3e471091c4",
    type: "COMPONENT_SET",
    description: "정확한 페이지 번호와 이전/다음 이동을 제공하는 숫자형 페이지네이션",
    variantCount: 28,
    variantAxes: { Mode: ["Default", "Fixed"], Size: ["Small", "Medium"], Pages: ["1", "2", "3", "4", "5", "6", "7"] },
    status: "planned",
  },
  {
    id: "loading-dot",
    displayName: "Loading Dot",
    figmaName: "Loading_Dot",
    nodeId: "10384:29778",
    componentKey: "b1ecfc5a18468daceeaaa41142ef26f896c0f67f",
    type: "COMPONENT_SET",
    description: "화면 이동이나 컴포넌트 내부 처리 중 상태를 점 애니메이션으로 알려주는 로딩 컴포넌트",
    variantCount: 6,
    variantAxes: { Mode: ["Default", "Fixed"], Size: ["Small", "Medium"], Color: ["Default", "White"] },
    status: "ready",
  },
  {
    id: "loading-circular",
    displayName: "Loading Circular",
    figmaName: "Loading_Circular",
    nodeId: "10384:29888",
    componentKey: "b24a5889bca4523ee97a36936574bf3abbee155c",
    type: "COMPONENT_SET",
    description: "Dot Loading을 사용할 수 없는 컴포넌트 내부 상황에서 사용하는 원형 로딩 컴포넌트",
    variantCount: 2,
    variantAxes: { Mode: ["Default", "Fixed"] },
    status: "ready",
  },
  {
    id: "toggle-switch",
    displayName: "Toggle Switch",
    figmaName: "Toggle Switch",
    nodeId: "7927:149092",
    componentKey: "707fb6a0b475122bef17b30346b9dfe6f211c50b",
    type: "COMPONENT_SET",
    description: "설정값을 ON/OFF로 즉시 변경하는 플랫폼별 스위치 컨트롤",
    variantCount: 24,
    variantAxes: { Mode: ["Default", "Fixed"], OS: ["iOS", "AOS"], Size: ["Small", "Medium"], Status: ["Off", "On", "Disabled"] },
    status: "ready",
  },
  {
    id: "tooltip",
    displayName: "Tooltip",
    figmaName: "Tooltip",
    nodeId: "7891:6903",
    componentKey: "51e3f2d3c3ea2ece4c8b084477cee852a10eb2da",
    type: "COMPONENT_SET",
    description: "특정 객체와 연결해 짧은 안내나 강조 내용을 표시하는 컴포넌트",
    variantCount: 96,
    variantAxes: { Mode: ["Default", "Fixed"], Size: ["Small", "Medium"], Color: ["Black", "White", "Primary"], Position: ["Top", "Top Left", "Top Right", "Right", "Bottom", "Bottom Left", "Bottom Right", "Left"] },
    status: "planned",
  },
  {
    id: "tag",
    displayName: "Tag",
    figmaName: "tag",
    nodeId: "30256:32826",
    componentKey: "bc5965253050f2719974ba59fab7b22b35a05b3f",
    type: "COMPONENT_SET",
    description: "콘텐츠의 속성, 카테고리, 상태를 짧은 키워드로 식별하는 정보 표시 컴포넌트",
    variantCount: 89,
    variantAxes: { Size: ["Small", "Medium"], Type: ["Filled", "Outlined"], Shape: ["Square", "Round"], Color: ["Gray", "Black", "Primary", "Red", "Orange", "Yellow", "Green", "Blue", "Purple", "Pink", "White", "Inverse"] },
    status: "planned",
  },
] as const satisfies readonly ChordComponentManifest[];

export type ChordComponentId = (typeof chordComponents)[number]["id"];

export function getChordComponent(id: ChordComponentId) {
  return chordComponents.find((component) => component.id === id);
}
