import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const root = resolve(new URL("..", import.meta.url).pathname);
const externalTokensDir = resolve(root, "../../../chord-design-system/tokens");

if (!existsSync(externalTokensDir)) {
  throw new Error(
    `Token source not found. Run from project root; expected: ${externalTokensDir}`
  );
}

const tokenFiles = [
  resolve(externalTokensDir, "color.json"),
  resolve(externalTokensDir, "size.json"),
  resolve(externalTokensDir, "shadow.json"),
  resolve(externalTokensDir, "typography.json"),
];
const semanticTypographyFile = resolve(externalTokensDir, "typography.semantic.json");
const outputPath = resolve(root, "src/styles/generated/tokens.css");

function cssVariableName(token) {
  return `--cds-${token.id
    .replace(/^token:/, "")
    .replace(/[./_]+/g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "")
    .toLowerCase()}`;
}

function cssValue(token, raw) {
  if (raw == null) return undefined;
  if (typeof raw === "number") {
    return token.type === "dimension" ? `${raw}px` : String(raw);
  }
  return String(raw);
}

function addVar(bucket, token, modeName) {
  const modeValue = token.values?.[modeName];
  if (!modeValue) return;
  const value = cssValue(token, modeValue.raw);
  if (!value) return;
  bucket.push(`  ${cssVariableName(token)}: ${value};`);
}

function semanticSlug(name) {
  return name.toLowerCase().replace(/[/_]+/g, "-").replace(/[^a-z0-9-]/g, "");
}

function buildSemanticVars(tokens) {
  const classes = [];
  for (const token of tokens) {
    const { fontFamily, fontSize, fontWeight, lineHeight } = token.refs ?? {};
    if (!fontFamily || !fontSize || !fontWeight || !lineHeight) continue;
    const slug = semanticSlug(token.name);
    classes.push(`.chord-text-${slug} {`);
    classes.push(`  font-family: var(${cssVariableName({ id: fontFamily })});`);
    classes.push(`  font-size: var(${cssVariableName({ id: fontSize })});`);
    classes.push(`  font-weight: var(${cssVariableName({ id: fontWeight })});`);
    classes.push(`  line-height: var(${cssVariableName({ id: lineHeight })});`);
    classes.push(`}`);
  }
  return { vars: [], classes };
}

const light = ['  --cds-token-build-status: "generated";'];
const dark = [];
const rootVars = [];

for (const tokenFile of tokenFiles) {
  const data = JSON.parse(readFileSync(tokenFile, "utf8"));
  for (const token of data.tokens ?? []) {
    addVar(light, token, "light");
    addVar(dark, token, "dark");
    addVar(rootVars, token, "web");
    addVar(rootVars, token, "mode-1");
  }
}

const semanticData = JSON.parse(readFileSync(semanticTypographyFile, "utf8"));
const { classes: semanticClasses } = buildSemanticVars(semanticData.tokens ?? []);

const composites = [
  "  --cds-system-shadow-lg: var(--cds-system-shadow-position-x-large) var(--cds-system-shadow-position-y-large) var(--cds-system-shadow-blur-large) var(--cds-system-shadow-spread-large) var(--cds-system-fixed-color-surface-default-100a);",
];

const css = [
  "/* This file is generated by scripts/build-tokens.mjs. */",
  ":root {",
  ...rootVars,
  ...composites,
  "}",
  "",
  ":root, [data-theme='light'] {",
  ...light,
  "}",
  "",
  "[data-theme='dark'] {",
  ...dark,
  "}",
  "",
  "/* Semantic typography utility classes */",
  ...semanticClasses,
  "",
].join("\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, css);
console.log(`tokens.css written → ${outputPath}`);
