#!/usr/bin/env node
// Builds tokens.css from Chord Design System token JSON files.
// Input: --tokens-dir or CHORD_TOKENS_DIR env var
// Output: --output (default: src/styles/tokens.css)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = resolve(__dirname, "..");

function parseArgs(argv) {
  const result = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      result[argv[i].slice(2)] = argv[i + 1];
      i++;
    }
  }
  return result;
}

const args = parseArgs(process.argv.slice(2));
const tokensDir =
  args["tokens-dir"] ||
  process.env.CHORD_TOKENS_DIR ||
  "/Users/jj.iee/Desktop/chord-design-system/tokens";
const outputPath = args["output"] || resolve(ROOT, "src/styles/tokens.css");

if (!existsSync(tokensDir)) {
  process.stderr.write(
    `Error: Chord Design System tokens directory not found:\n  ${tokensDir}\n\nSet CHORD_TOKENS_DIR or pass --tokens-dir <path>.\nExample:\n  CHORD_TOKENS_DIR=/path/to/chord-design-system/tokens node scripts/build-tokens.mjs\n`
  );
  process.exit(2);
}

const tokenFiles = [
  resolve(tokensDir, "color.json"),
  resolve(tokensDir, "size.json"),
  resolve(tokensDir, "typography.json"),
  resolve(tokensDir, "shadow.json"),
  resolve(tokensDir, "breakpoint.json"),
];
const semanticTypographyFile = resolve(tokensDir, "typography.semantic.json");

function cssVariableName(token) {
  return `--cds-${token.id
    .replace(/^token:/, "")
    .replace(/[./_]+/g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "")
    .toLowerCase()}`;
}

function cssValue(token, raw) {
  if (raw == null) return undefined;
  if (typeof raw === "number") {
    return token.type === "dimension" ? `${raw}px` : String(raw);
  }
  return String(raw);
}

function addVar(bucket, token, modeName) {
  const modeValue = token.values?.[modeName];
  if (!modeValue) return;
  const value = cssValue(token, modeValue.raw);
  if (!value) return;
  bucket.push(`  ${cssVariableName(token)}: ${value};`);
}

function semanticSlug(name) {
  return name.toLowerCase().replace(/[/_]+/g, "-").replace(/[^a-z0-9-]/g, "");
}

function buildSemanticVars(tokens) {
  const classes = [];
  for (const token of tokens) {
    const { fontFamily, fontSize, fontWeight, lineHeight } = token.refs ?? {};
    if (!fontFamily || !fontSize || !fontWeight || !lineHeight) continue;
    const slug = semanticSlug(token.name);
    classes.push(`.chord-text-${slug} {`);
    classes.push(`  font-family: var(${cssVariableName({ id: fontFamily })});`);
    classes.push(`  font-size: var(${cssVariableName({ id: fontSize })});`);
    classes.push(`  font-weight: var(${cssVariableName({ id: fontWeight })});`);
    classes.push(`  line-height: var(${cssVariableName({ id: lineHeight })});`);
    classes.push(`}`);
  }
  return classes;
}

const light = ['  --cds-token-build-status: "generated";'];
const dark = [];
const rootVars = [];

// breakpoint and shadow tokens that don't vary by theme go in :root
const themeInvariantPrefixes = ["token:system.breakpoint.", "token:system.shadow."];

for (const tokenFile of tokenFiles) {
  const data = JSON.parse(readFileSync(tokenFile, "utf8"));
  for (const token of data.tokens ?? []) {
    if (themeInvariantPrefixes.some((p) => token.id.startsWith(p))) {
      addVar(rootVars, token, "light"); // same value in both modes
    } else {
      addVar(light, token, "light");
      addVar(dark, token, "dark");
      addVar(rootVars, token, "web");
      addVar(rootVars, token, "mode-1");
    }
  }
}

// Composite shadow-lg shorthand — color: system/fixed_color/surface/default-100a
rootVars.push(
  "  --cds-system-shadow-large: var(--cds-system-shadow-position-x-large) var(--cds-system-shadow-position-y-large) var(--cds-system-shadow-blur-large) var(--cds-system-shadow-spread-large) var(--cds-system-fixed-color-surface-default-100a);"
);

const semanticData = JSON.parse(readFileSync(semanticTypographyFile, "utf8"));
const semanticClasses = buildSemanticVars(semanticData.tokens ?? []);

const css = [
  "/* This file is generated by scripts/build-tokens.mjs. Do not edit manually. */",
  "/* Run: bash scripts/sync_tokens.sh  to regenerate from chord-design-system/tokens */",
  ":root {",
  ...rootVars,
  "}",
  "",
  ":root, [data-theme='light'] {",
  ...light,
  "}",
  "",
  "[data-theme='dark'] {",
  ...dark,
  "}",
  "",
  "/* Semantic typography utility classes */",
  ...semanticClasses,
  "",
].join("\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, css);
console.log(`build-tokens: tokens.css written → ${outputPath}`);
