#!/bin/bash

# * 사용방법
# ```
# $ ./update-figma-res
# # 강제업데이트
# $ ./update-figma-res --force
# # 특정 아이콘만 업데이트
# $ ./update-figma-res ic_light_theme_medium ic_dark_theme_medium
# ```

SCRIPT_PATH=$(dirname "$0")
VENV_PATH="$SCRIPT_PATH/.venv"
PYTHON_BIN="$VENV_PATH/bin/python"

install_python_module() {
    module_name=$1

    if "$PYTHON_BIN" -m pip show $module_name >/dev/null 2>&1; then
        echo "$module_name is already installed"
    else
        "$PYTHON_BIN" -m pip install $module_name

        if [ $? -eq 0 ]; then
            echo "Successfully installed $module_name"
        else
            echo "Failed $module_name"
        fi
    fi
}

if [ ! -x "$PYTHON_BIN" ]; then
    python3 -m venv "$VENV_PATH"
fi

install_python_module requests

case "$1" in
    -f|--force)
        shift
        "$PYTHON_BIN" "$SCRIPT_PATH/update-figma-res.py" --force "$@"
        ;;
    *)
        "$PYTHON_BIN" "$SCRIPT_PATH/update-figma-res.py" "$@"
        ;;
esac
