import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const root = resolve(new URL("..", import.meta.url).pathname);
const tokenFiles = [
  "tokens/tokens.color.v1.0.json",
  "tokens/tokens.size.v1.0.json",
  "tokens/tokens.typography.v1.0.json",
];
const outputPath = resolve(root, "src/styles/generated/tokens.css");

function cssVariableName(token) {
  return `--cds-${token.id
    .replace(/^token:/, "")
    .replace(/[./_]+/g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "")
    .toLowerCase()}`;
}

function cssValue(token, raw) {
  if (raw == null) return undefined;
  if (typeof raw === "number") {
    return token.type === "dimension" ? `${raw}px` : String(raw);
  }
  return String(raw);
}

function addVar(bucket, token, modeName) {
  const modeValue = token.values?.[modeName];
  if (!modeValue) return;
  const value = cssValue(token, modeValue.raw);
  if (!value) return;
  bucket.push(`  ${cssVariableName(token)}: ${value};`);
}

const light = ['  --cds-token-build-status: "generated";'];
const dark = [];
const rootVars = [];

for (const tokenFile of tokenFiles) {
  const data = JSON.parse(readFileSync(resolve(root, tokenFile), "utf8"));
  for (const token of data.tokens ?? []) {
    addVar(light, token, "light");
    addVar(dark, token, "dark");
    addVar(rootVars, token, "web");
    addVar(rootVars, token, "mode-1");
  }
}

const css = [
  "/* This file is generated by scripts/build-tokens.mjs. */",
  ":root, [data-theme='light'] {",
  ...light,
  "}",
  "",
  "[data-theme='dark'] {",
  ...dark,
  "}",
  "",
  ":root {",
  ...rootVars,
  "}",
  "",
].join("\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, css);
